In [1]:
import numpy as np

In [2]:
theta = np.array([1,2,5])
x = np.array([4,5,1])
y = -1

np.matmul(theta, x) 

19

In [3]:
def hinge_loss_single(feature_vector, label, theta, theta_0):

    return max(0, 1 - label * (np.matmul(theta,feature_vector) + theta_0))

In [4]:
x = np.array([[1,2]]).transpose()
y = np.array([[3,4]])

In [5]:
print(x.shape)
print(y.shape)

(2, 1)
(1, 2)


In [6]:
print(x)
print(y)

[[1]
 [2]]
[[3 4]]


In [7]:
z = x @ y
print(z)

[[3 4]
 [6 8]]


In [8]:
theta = np.array([[2,1]]).transpose()
print(theta)

[[2]
 [1]]


In [17]:
feature_vector = np.array([[1, 2], [1, 2]])
label, theta, theta_0 = np.array([1, 1]), np.array([-1, 1]), -0.2
exp_res = 1 - 0.8

In [18]:
agreement_vector = label * (feature_vector @ theta + theta_0)
agreement_vector

array([0.8, 0.8])

In [19]:
loss_vector = np.maximum(0, 1 - agreement_vector)
loss_vector

array([0.2, 0.2])

In [20]:
avg_loss = np.average(loss_vector)
avg_loss

0.19999999999999996

In [22]:
feature_vector = np.array([1, 2])
label, theta, theta_0 = 1, np.array([-1, 1]), -1.5
exp_res = (np.array([0, 3]), -0.5)


# feature_vector = np.array([1, 2])
# label, theta, theta_0 = 1, np.array([-1, 1]), -1
# exp_res = (np.array([0, 3]), 0)

In [23]:
agreement = label * (feature_vector @ theta + theta_0)
agreement

-0.5

In [26]:
A = np.array([[1,2,3],[4,5,6]])
A[1]

array([4, 5, 6])

In [33]:
theta = np.zeros(A.shape[1])
theta.shape


(3,)