In [2]:
import numpy as np

### 4. Intro to Numpy
Randomization

In [4]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    return np.random.random([n,1])
    raise NotImplementedError

randomization(5)

array([[0.56969357],
       [0.755573  ],
       [0.07594016],
       [0.06672602],
       [0.86668859]])

Operations

In [5]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    A, B = np.random.random([h,w]), np.random.random([h,w])
    s = A + B
    return A, B, s
    raise NotImplementedError

operations(2,3)

(array([[0.02144954, 0.44620467, 0.42705005],
        [0.88078357, 0.07867086, 0.42715041]]),
 array([[0.29570833, 0.38134556, 0.07833561],
        [0.52496615, 0.54195719, 0.47828489]]),
 array([[0.31715787, 0.82755023, 0.50538566],
        [1.40574973, 0.62062805, 0.9054353 ]]))

Norm

In [6]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    return np.linalg.norm(A+B)
    raise NotImplementedError

dim = [3, 1]
A, B = np.random.random(dim), np.random.random(dim)
norm(A, B)

1.7486114909714816

### 5. Exercise
Neural Network

In [42]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    
    return np.tanh(np.matmul(np.transpose(inputs),weights))

x = np.array([1,2])
w = np.array([0.5, 0.75])

neural_network(x,w)


0.9640275800758169

### 6. Vectorize function
Scalar function

In [9]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    return x*y if x < y else x/y
    raise NotImplementedError

scalar_function(4,2)

2.0

Vector function

In [12]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """

    # def _scalar_function(x, y):
    #     return x*y if x < y else x/y

    # def _vector_function(scalar_function):
    #     func = scalar_function
    #     return np.vectorize(func)

    # return _vector_function(_scalar_function)(x, y)

    return np.vectorize(lambda x,y: x*y if x<y else x/y)(x,y)

dim = [2,1]
x, y = np.random.random(dim), np.random.random(dim)

vector_function(x, y)


array([[0.89480634],
       [1.3569368 ]])