In [113]:
import numpy as np


def rectified_linear_unit(x):
    """ Returns the ReLU of x, or the maximum between 0 and x."""
    return max(0,x)

def rectified_linear_unit_derivative(x):
    """ Returns the derivative of ReLU."""
    return 0 if x == 0 else 1

def output_layer_activation(x):
    """ Linear function, returns input as is. """
    return x

def output_layer_activation_derivative(x):
    """ Returns the derivative of a linear function: 1. """
    return 1

In [202]:
# DO NOT CHANGE PARAMETERS (Initialized to floats instead of ints)
input_to_hidden_weights = np.matrix('1. 1.; 1. 1.; 1. 1.')
hidden_to_output_weights = np.matrix('1. 1. 1.')
biases = np.matrix('0.; 0.; 0.')
learning_rate = .001
epochs_to_train = 10

### Forward propagation ###
# input_values = np.matrix([[x1],[x2]]) # 2 by 1
input_values = np.matrix([[2],[1]])
y = 10

# Calculate the input and activation of the hidden layer
hidden_layer_weighted_input = np.matmul(input_to_hidden_weights, input_values) # (3 by 1 matrix)
hidden_layer_activation = np.vectorize(rectified_linear_unit)(hidden_layer_weighted_input) # (3 by 1 matrix)
# output = hidden_to_output_weights @ hidden_layer_activation
output = np.matmul(hidden_to_output_weights, hidden_layer_activation)
activated_output = np.vectorize(output_layer_activation)(output)


In [203]:
# print(input_to_hidden_weights)
# print(input_values)
# print(hidden_layer_weighted_input)
print(hidden_to_output_weights)
print(hidden_layer_activation)
print(output)
print(activated_output)

[[1. 1. 1.]]
[[3.]
 [3.]
 [3.]]
[[9.]]
[[9.]]


In [167]:
### Backpropagation ###

# Compute gradients
output_layer_error = activated_output - y
hidden_layer_error = (
    np.multiply(
        np.vectorize(rectified_linear_unit_derivative)(hidden_layer_activation),
        hidden_to_output_weights.transpose()
    )
    * activated_output
)

print(np.vectorize(rectified_linear_unit_derivative)(hidden_layer_activation))
print(hidden_to_output_weights)
print(activated_output)
print(hidden_layer_error)


[[1]
 [1]
 [1]]
[[1. 1. 1.]]
[[9.]]
[[9.]
 [9.]
 [9.]]


In [187]:
bias_gradients = hidden_layer_error
hidden_to_output_weight_gradients = np.multiply(hidden_layer_activation, output_layer_error)

# print(hidden_layer_activation)
# print(output_layer_error)
print(hidden_to_output_weight_gradients)
# print(hidden_layer_error)
# print(type(hidden_layer_error))
# print(np.multiply(input_values.transpose(), hidden_layer_error))




[[-3.]
 [-3.]
 [-3.]]


In [ ]:
# Use gradients to adjust weights and biases using gradient descent
self.biases = self.biases - self.learning_rate * bias_gradients
self.input_to_hidden_weights = self.input_to_hidden_weights - self.learning_rate * input_to_hidden_weight_gradients
self.hidden_to_output_weights = self.hidden_to_output_weights - self.learning_rate * hidden_to_output_weight_gradients